### ISSUE TITLE
scipy==1.2.0 causes dependency errors

### ISSUE THREAD

**Issue by davidpbowe** [CamDavidsonPilon/lifetimes#274]
Installing lifetimes with python3.7 caused the below dependency error.

`Traceback (most recent call last):
  File "UserStatus.py", line 9, in <module>
    from lifetimes.datasets import load_transaction_data
  File "~/.virtualenvs/analysis/lib/python3.7/site-packages/lifetimes/__init__.py", line 5, in <module>
    from .fitters.beta_geo_fitter import BetaGeoFitter
  File "~/.virtualenvs/analysis/lib/python3.7/site-packages/lifetimes/fitters/beta_geo_fitter.py", line 9, in <module>
    from autograd.scipy.special import gammaln, beta, gamma
  File "~/.virtualenvs/analysis/lib/python3.7/site-packages/autograd/scipy/__init__.py", line 7, in <module>
    from . import misc
  File "~/.virtualenvs/analysis/lib/python3.7/site-packages/autograd/scipy/misc.py", line 7, in <module>
    logsumexp = primitive(scipy.misc.logsumexp)
AttributeError: module 'scipy.misc' has no attribute 'logsumexp'`

Pip install seemed to have installed scipy==1.2.0 where the location of the logsumexp function has changed. Downgrading to scipy==1.1.0 solves the issue

**Comment by teresadong** [comment]
I believe scipy.misc.logsumexp is deprecated according to: https://github.com/HIPS/autograd/issues/501
scipy.special.logsumexp I think is the correct new path

**Comment by aprotopopov** [comment]
Due to that error, I suggest modifying requirements.txt for now for the autograd package to install it from git from [fix commit](https://github.com/HIPS/autograd/commit/4ec5aede380c5accf20afd4f4a96d59f1a9cd1df). 

```
-e git://github.com/HIPS/autograd.git@4ec5aede380c5accf20afd4f4a96d59f1a9cd1df#egg=autograd
```
