### ISSUE TITLE
Pip Install Error

### ISSUE THREAD

**Issue by tshauck** [CamDavidsonPilon/lifetimes#3]
Hi,

I'm trying to pip install, and getting the following error.  I also tried it from a fresh conda env with the same results.  I can install if from `python setup.py install`, so maybe the readme isn't available to pip at install time?  Though not really sure...

Here's the traceback:

```
Collecting lifetimes
  Using cached Lifetimes-0.1.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/setup.py", line 18, in <module>
        long_description=read('README.md'),
      File "/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/setup.py", line 18, in <module>

        long_description=read('README.md'),

      File "/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/setup.py", line 6, in read

        return open(os.path.join(os.path.dirname(__file__), fname)).read()

    IOError: [Errno 2] No such file or directory: '/private/var/folders/7b/trxdysx57xz95389p87cbhqrxgb3nq/T/pip-build-XwlQNs/lifetimes/README.md'
```

Here's the conda env.

```
Current conda install:

             platform : osx-64
        conda version : 3.8.3
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /Users/thauck/bin/miniconda  (writable)
  default environment : /Users/thauck/projects/ltv/env
     envs directories : /Users/thauck/bin/miniconda/envs
        package cache : /Users/thauck/bin/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : /Users/thauck/.condarc
    is foreign system : False
```

**Comment by CamDavidsonPilon** [comment]
Thanks for the heads up @tshauck, I'll get this fixed immediately.

**Comment by CamDavidsonPilon** [comment]
I just pushed a new version 0.1.2 to pypi. It install successfully for me on a clean virtualenv. 

![screen shot 2015-02-22 at 10 34 10](https://cloud.githubusercontent.com/assets/884032/6319091/5db6e334-ba7e-11e4-9d9d-887f6b8979d2.png)
